/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.coe.info6205.life.custom;

import edu.neu.coe.info6205.life.base.Point;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author lihangzhou
 */
public class WorldFrame extends javax.swing.JFrame {

    /**
     * Creates new form TempFrame
     */
    GamePanel gamePanel;
    boolean autoRunning = false;
    AutoRun autoRun;

    public WorldFrame() {
        initComponents();
        wholePanel.setSize(30 * 3, 30 * 3);
        List<Point> points = new ArrayList<>();
        points.add(new Point(0, 0));
        points.add(new Point(1, 0));
        points.add(new Point(2, 0));
        points.add(new Point(2, -1));
        points.add(new Point(1, -2));
        gamePanel = new GamePanel(30, 30, points);
        setGamePanel();
    }

    public WorldFrame(int row, int col, List<Point> points) {
        initComponents();
        wholePanel.setSize(row * 3, col * 3);
        gamePanel = new GamePanel(row, col, points);
        setGamePanel();
    }

    private void setGamePanel() {
        CardLayout layout = (CardLayout) wholePanel.getLayout();

        wholePanel.add("GamePanel", gamePanel);
        layout.next(wholePanel);
    }

    class AutoRun extends Thread {

        long sleepTime;

        public AutoRun(long sleepTime) {
            this.sleepTime = sleepTime;
        }

        @Override
        public void run() {
            try {
                while (true) {
                    doTick();
                    Thread.sleep(sleepTime);
                }
            } catch (InterruptedException ex) {
                Logger.getLogger(WorldFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }
    
    public void doTick(){
        this.lblGen.setText("Gen: "+gamePanel.tick());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wholePanel = new javax.swing.JPanel();
        btnTick = new javax.swing.JButton();
        checkBoxAuto = new javax.swing.JCheckBox();
        lblGen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wholePanel.setLayout(new java.awt.CardLayout());

        btnTick.setText("Tick");
        btnTick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTickActionPerformed(evt);
            }
        });

        checkBoxAuto.setText("Auto");

        lblGen.setText("Gen:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnTick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGen)
                .addContainerGap(443, Short.MAX_VALUE))
            .addComponent(wholePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTick)
                    .addComponent(checkBoxAuto)
                    .addComponent(lblGen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wholePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTickActionPerformed
        // TODO add your handling code here:
        if (autoRunning) {
            autoRun.interrupt();
            autoRunning = false;

        } else if (!checkBoxAuto.isSelected()) {
            doTick();
        } else {
            autoRun = new AutoRun(500L);
            autoRun.start();
            autoRunning = true;
        }

    }//GEN-LAST:event_btnTickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorldFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorldFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorldFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorldFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorldFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTick;
    private javax.swing.JCheckBox checkBoxAuto;
    private javax.swing.JLabel lblGen;
    private javax.swing.JPanel wholePanel;
    // End of variables declaration//GEN-END:variables
}
